name: jedi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # 下拉刷新、上拉加载更多
  # https://pub.dartlang.org/packages/pulltorefresh_flutter
  # pulltorefresh_flutter: "^0.1.9"

  # 对图片使用sqflite进行缓存管理
  # https://pub.dev/packages/cached_network_image#-readme-tab-
  cached_network_image: ^0.8.0

  # 极光推送官方支持的插件
  # https://pub.dartlang.org/packages/jpush_flutter
  jpush_flutter: 0.0.11

  # Http请求库，支持拦截器、请求取消、Cookie管理、文件上传/下载、超时、自定义适配器等
  # https://pub.dev/packages/dio#-readme-tab-
  dio: ^2.1.3

  # 允许Flutter与本机WebView通信的插件
  # https://pub.dartlang.org/packages/flutter_webview_plugin
  flutter_webview_plugin: ^0.3.3

  # 阿里百川电商SDK在Flutter上的实现
  # https://pub.dartlang.org/packages/nautilus#-readme-tab-
  # nautilus: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 要向应用程序添加资产，请添加资产部分，如下所示：
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/navigation_home.png
    - assets/navigation_home_selected.png
    - assets/navigation_classify.png
    - assets/navigation_classify_selected.png
    - assets/navigation_society.png
    - assets/navigation_society_selected.png
    - assets/navigation_earnings.png
    - assets/navigation_earnings_selected.png
    - assets/navigation_my.png
    - assets/navigation_my_selected.png
    - assets/app_bar_more.png
    - assets/app_bar_service.png
    - assets/app_bar_scan.png
    - assets/app_bar_service_angle.png
    - assets/app_bar_plate_1.png
    - assets/app_bar_plate_2.png
    - assets/app_bar_plate_3.png
    - assets/featured_headlines_title.png
    - assets/home_porcelain_backplane_1.png
    - assets/home_porcelain_backplane_2.png
    - assets/home_porcelain_backplane_3.png
    - assets/home_porcelain_backplane_4.png
    - assets/hot_list_sign.png
    - assets/home_roll_backplane.png
    - assets/recommend_you_title.png
    - assets/recommended_volume.png
    - assets/recommended_volume_2.png
    - assets/recommended_volume_3.png
    - assets/app_bar_scan_gray.png
    - assets/app_bar_service_gray.png
    - assets/community_title.png
    - assets/community_sharing.png
    - assets/community_label.png
    - assets/income_bottom_plate.png
    - assets/my_backboard.png
    - assets/my_message.png
    - assets/my_income.png
    - assets/my_order.png
    - assets/my_fans.png
    - assets/my_invitation.png
    - assets/my_common_corner.png
    - assets/my_newbie_guide.png
    - assets/my_yue_collection.png
    - assets/my_official_announcement.png
    - assets/my_feedback.png
    - assets/my_about_us.png
    - assets/my_settings.png
    - assets/super_member_logo.png
    - assets/choose_my_order.png
    - assets/choose_subordinate_order.png
    - assets/my_order_rectangle.png
    - assets/details_share_gradient.png
    - assets/details_coupon_gradient.png
    - assets/details_discount_gradient.png
    - assets/details_white_back.png
    - assets/details_white_collection.png
    - assets/details_white_more.png
    - assets/details_black_back.png
    - assets/details_black_collection.png
    - assets/details_black_more.png
    - assets/limited_bar_plate_1.png
    - assets/limited_bar_plate_2.png
    - assets/limited_bar_title.png
    - assets/limited_estimated_price.png
    - assets/white_placeholder.png
    - assets/refresh.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: PingFangRegular
      fonts:
        - asset: fonts/苹方黑体-准-简.ttf
    - family: PingFangMedium
      fonts:
        - asset: fonts/苹方黑体-中黑-简.ttf
    - family: PingFangBold
      fonts:
        - asset: fonts/苹方黑体-中粗-简.ttf
